Vue.createApp({
    data(){
        return{
            producto:'',
            carrito:[
                'cebolla',
                'tomate',
                'papas'
            ]
        }
    }
}).mount('#App')